agot_dragon_designer_events_l_german 0.3.0.3
KODEX-Mods/CK3AGOT-Deutsch pull request #55
Opened 2024-09-07 13:49 UTC by Nero55667

2024-09-09 19:59 UTC, Dillo234 requested changes
Hey @Nero55667,
Mir sind sofort zwei Dinge aufgefallen. Erstens hat deine übersetzte File die falsche Anzahl an Zeilen. Schau mal bitte woran das liegt, vielleicht hast du etwas aus Versehen gedoppelt oder so. Und zweitens ist mir ins Auge gesprungen, dass Du bei den Anreden nicht konsequent warst. Du hast mal "Du" und mal "Sie". Richtig ist aber, immer wenn der Spieler angesprochen wird (z.B. "Ihr sucht Euch Euren Drachen aus"), wird "Ihr/Euch" benutzt. Und auch, wenn Charaktere miteinander interagieren, außer natürlich Freunde, Kameraden, Verwandte etc.
Bitte schau nochmal durch und passe das so an 🙂 🤝

2024-09-11 17:39 UTC, Dillo234 commented
> Hey @Nero55667, Mir sind sofort zwei Dinge aufgefallen. Erstens hat deine übersetzte File die falsche Anzahl an Zeilen. Schau mal bitte woran das liegt, vielleicht hast du etwas aus Versehen gedoppelt oder so. Und zweitens ist mir ins Auge gesprungen, dass Du bei den Anreden nicht konsequent warst. Du hast mal "Du" und mal "Sie". Richtig ist aber, immer wenn der Spieler angesprochen wird (z.B. "Ihr sucht Euch Euren Drachen aus"), wird "Ihr/Euch" benutzt. Und auch, wenn Charaktere miteinander interagieren, außer natürlich Freunde, Kameraden, Verwandte etc. Bitte schau nochmal durch und passe das so an 🙂 🤝

Mir ist gerade aufgefallen, dass der Unterschied der Zeilenanzahl wohl Leerzeilen geschuldet, die bei dir reingerutscht sind. Diese also einfach fix suchen und entfernen, wenn du eh gerade bei der Bearbeitung bist :)

2024-09-12 13:09 UTC, Nero55667 commented
Ok dann werde ich das nochmal überprüfen

2025-04-02 21:42 UTC, Dillo234 approved these changes

2026-03-08 14:00 UTC, Dillo234 commented
Geschlossen, weil die Datei komplett mit KI bearbeitet wurde, das Ergebnis Schwachsinn ist und nicht mehr reagiert wurde

2026-03-08 14:00 UTC, closed without merging